config/routes.rb
SoupToBits::Application.routes.draw do

  resources :soups
  resources :categories

  root to:"categories#index"
  get '/allcategories' => redirect('/')
  get "/soups/:id/toggle_feautred", to: "soups#toggle_featured", as: :toggle_featured

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :soups

	validates :name,
				presence: true
end

app/models/soup.rb
class Soup < ActiveRecord::Base
	belongs_to :category

	validates :name,
			  	presence: true,
			  	uniqueness: true
	validates  :featured,
			  	presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	before_action :fetch_category, only: [:update, :edit, :show, :destroy]

	def index
		@categories = Category.all
	end
	
	def show
		respond_to do |format|
			format.html
			format.json { render json: @category }
			format.xml 	{ render xml: @category }
		end
	end

	def new
	end

	def update
	end
	
	def edit
	end

	def destroy
	end

	private
	def fetch_category
		@category = Category.find(params[:id])
	end


end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
	before_action :fetch_soup, only: [:show, :toggle_featured]

	def index
		@soups = Soup.all

		respond_to do |format|
			format.html
			format.json { render json: @soups}
		end
	end

	def show
		respond_to do |format|
			format.html
			format.json {render json: @soup}
			format.xml	{render xml: @soup}
		end
		
	end

	def toggle_featured
		@soup.toggle!(:featured)
		flash[:notice] = "Successfully changed the featured flag"
		redirect_to(@soup)
	end

	def fetch_soup
		@soup = Soup.find(params[:id]) 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
	<% @categories.each do |category| %>
	<li> <%= link_to category.name, category %> (<%= category.soups.count %>) </li>
	<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
	<% @category.soups.each do |soup| %>
	<li> <%= link_to soup.name, soup %> </li>
	<% end %>
</ul>

<p><%= link_to "Categories", categories_path %> </p>
<p><%= link_to "Soups", soups_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoupToBits</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
	<p> <%= flash[:notice] %> </p>
	<% end %>

<%= yield %>

</body>
</html>

app/views/soups/index.html.erb
<h1>Soups</h1>

<ul>
	<% @soups.each do |soup| %>
	<li><%= link_to soup.name, soup %> </li>
	<% end %>

</ul>

app/views/soups/show.html.erb
<h1> <%= @soup.name %> </h1>

<% if @soup.featured? %>
	<p>This soup is featured this month.</p>
<% else %>
	<p>This soup is not in season.</p>
<% end %>

<% if params[:admin] == "true" %>
<p> <%= link_to "Toggle Feautre", toggle_featured_path(@soup) %> </p>
<% end %>

<p> <%= link_to "Soups", soups_path %> </p>
<p> <%=link_to "Categories", categories_path %></p>